# Generated by Django 5.1.6 on 2025-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
